server:
  port: 8080
spring:
  application:
    name: Nokia Interview
  h2:
    console:
      enabled: true
      path: /h2
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:h2:mem:test_database
    username: sa
    password:
    driverClassName: org.h2.Driver


